### ISSUE TITLE
Pip install

### ISSUE THREAD

**Issue by HarbingerOfFire** [HarbingerOfFire/bivittatusDB#13]
@ScriptSlayer0 
In case you haven't seen it, I wanted to let you know that the project has been published and linked to PyPi, which means it can be installed using pip. We will have to run checks after releases to make sure our edits don't mess up the pip release.

**Comment by ScriptSlayer0** [comment]
Good, I have seen that you were working on that.

**Comment by HarbingerOfFire** [comment]
Yeah, I finally got it working today. My last error was that it wasn't including the lib_bdb.so when building the whl, which meant pip never installed it. That took a second to fix
