### ISSUE TITLE
Move to GCM for Security

### ISSUE THREAD

**Issue by HarbingerOfFire** [HarbingerOfFire/bivittatusDB#19]
![image](https://github.com/user-attachments/assets/646aacf6-2408-4a2d-bc6e-02efb6de2008)
![image](https://github.com/user-attachments/assets/783a2633-3d3e-486d-8539-318dc4f61522)
![image](https://github.com/user-attachments/assets/44de2c34-636a-4227-9756-d850f511a564)

**Comment by ScriptSlayer0** [comment]
I have the solution of that

**Comment by HarbingerOfFire** [comment]
Thanks, I thought you might have saw it since Sonarcloud is throwing it.
