### ISSUE TITLE
File handler compatability

### ISSUE THREAD

**Issue by HarbingerOfFire** [HarbingerOfFire/bivittatusDB#28]
**Describe the solution you'd like**
Certain classes require a input object that has a `write` or `read` method, which means that the object is a ReadableBuffer or SupportsWrite object. My goal with feature is to make it support those features as close as possible.

**Additional context**
So far i have been able to mimic the following functions:
-read
-readline
-readlines
-write
-seek
-tell
-readable
-writable
-seekable

Are there any other methods I should add for more compability? 

As of now, here is the current implementation which will  be used in an example file:
```python
#make sure to run inside the same directory as BivittatusDB, not the example directory.

import BivittatusDB as bdb

#drop pre-existing databases (for best practice and to prevent errors)
try: bdb.drop("test")
except: pass

#initialize the database
test_db=bdb.database("test").init()

#create a new table 
tb1=test_db.New_table("table1", #name "table1"
                       ("id", "name"), #columns are called "id" and "name"
                       (int(), str()), #id holds int, and name holds str
                       "id") #id will be the primary key

#add data to the table
tb1.write((1, "Alice"))
tb1.write((2, "Bob"))

#the write function is compatible with using the file argument of print
print((3,"Cindy"), file=tb1)

#Read data from a table
#read all data (prints raw)
print(tb1.read())

#Read one line at a time
print(tb1.readline())
print(tb1.readline())
print(tb1.readline())

#Read a specific line
print(tb1.readline(1))

#change position
#Postion options
#   0 = File beginning
#   1 = Current Position
#   2 = End of File
tb1.seek(0,0) #0 lines from the begging of the file

#get current position
print(tb1.tell())

#Read several lines starting at current position
print(tb1.readlines(2))

```

**Comment by HarbingerOfFire** [comment]
https://github.com/HarbingerOfFire/bivittatusDB/wiki/dbed-0003

**Comment by HarbingerOfFire** [comment]
Branch with sample implementation:
https://github.com/HarbingerOfFire/bivittatusDB/tree/File-Methods

**Comment by ScriptSlayer0** [comment]
@HarbingerOfFire There are more methods that can be added:
1. **flush()**: This method is used to flush the internal buffer of a file. When you write data to a file, it is often stored in a buffer before being written to the disk. The `flush()` method forces the buffer to be written to the disk immediately, ensuring that all data is saved.

```
# Add data to the table and ensure it is written immediately
tb1.write((4, "David"))
tb1.flush()  # Ensures that the data is written to disk immediately
```

    
2. **truncate()**: This method is used to resize the file to a specified length. If the specified length is shorter than the current file size, the file is truncated, and data beyond the specified length is lost. If the specified length is longer, the file is extended, and the new space is filled with null bytes.
```
# Truncate the table to a specific size
with open('test/table1', 'a+') as file:
    file.truncate(10)  # Resize the file to 10 bytes
```

3. **isatty()**: This method checks if the file descriptor is connected to a terminal device. It returns `True` if the file descriptor is connected to a terminal, and `False` otherwise. This is often used to determine if the output is being redirected to a file or another device.
```
import sys

# Check if the standard output is connected to a terminal
if sys.stdout.isatty():
    print("Output is a terminal")
else:
    print("Output is not a terminal")
```
4. **fileno()**: This method returns the file descriptor associated with the file object. A file descriptor is a low-level integer handle used to identify an open file. This method is useful when you need to perform low-level operations on the file.
```
import os

# Obtain the file descriptor associated with the table
with open('test/table1', 'a+') as file:
    fd = file.fileno()  # Obtain the file descriptor
    print(f"File descriptor: {fd}")
```
5. **detach()**: This method is used to detach the underlying binary buffer from a text stream. After detaching, the text stream becomes unusable, and you can work directly with the binary buffer. This is often used in advanced I/O operations where you need direct access to the binary data.
```
import io

# Create a text stream
text_stream = io.TextIOWrapper(io.BytesIO(b"Hello, World!"))
# Detach the binary buffer
binary_buffer = text_stream.detach()
print(binary_buffer.getvalue())  # Access the binary data directly
```
**We can discuss about this implementations.**

**Comment by HarbingerOfFire** [comment]
I actually forgot I included truncate, and I can easily add flush. 

Truncate actually truncated by line instead of bytes for a more usable case.

**Comment by HarbingerOfFire** [comment]
Ok, I added flush and detach based on common sense implementation. However, I think more discussion is needed for isatty() and fileno().
Do you think it's possible/feasible to attach a table to terminal output? if so, what would you suggest for this?
Also, file descriptors are used by the operating system to determine what file is running, so how would we create a file descriptor that points to an object instead of a file?

**Comment by ScriptSlayer0** [comment]
I did a quick consultation for this case and it seems that I don't see it as very easy or feasible for this case.

**Comment by HarbingerOfFire** [comment]
Yeah, I think we'll leave it out for now. I put a clause in the dbed about it so hopefully one day it could work.

**Comment by HarbingerOfFire** [comment]
Actually just got an idea. We can create a log file that can include certain information and use that file as a makeshift stdout 

https://chatgpt.com/share/56dceca4-7837-4dc5-ba43-8b15db354ab5

**Comment by ScriptSlayer0** [comment]
To read the latest events from the log looks very good

**Comment by HarbingerOfFire** [comment]
Yeah for security it would only read events from the current session

**Comment by HarbingerOfFire** [comment]
Ok method implemented, though no logs will be created yet

**Comment by ScriptSlayer0** [comment]
I modificated a little bit show() on bdb_agregate.py:
Now looks like:

```
def show(database: str):
    if not os.path.isdir(database):
        print(f"Directory '{database}' does not exist.")
        return []

    try:
        files = os.listdir(database)
        tables = [file[:-5] for file in files if file.endswith(".pydb")]
        return tables
    except PermissionError:
        print(f"You do not have permission to access the directory '{database}'.")
        return []
    except Exception as e:
        print(f"An error occurred while listing files: {e}")
        return []
```
I will show you how works with a real table:

https://github.com/user-attachments/assets/1e22a7c7-6474-4204-ab77-e175aa12aab7

The commit will be done in the branch File-Methods

**Comment by ScriptSlayer0** [comment]
Commit to reproduce the demo video: 82b74562d8d381673dcd6a7147e0f42978876b08

**Comment by HarbingerOfFire** [comment]
OK, I think we should go in and implement the log files, probably replacing infomessage

**Comment by ScriptSlayer0** [comment]
@HarbingerOfFire Any idea about this:
`Exception ignored in: <function table.__del__ at 0x000001ECFC6EC5E0>
Traceback (most recent call last):
  File "d:\github\bivittatusDB\BivittatusDB\BDB_tb.py", line 38, in __del__
    self.stop_log()
  File "d:\github\bivittatusDB\BivittatusDB\BDB_tb.py", line 35, in stop_log
    self.logger.stop()
  File "d:\github\bivittatusDB\BivittatusDB\tty_log.py", line 47, in stop
    self.thread.join()
  File "C:\Users\Unai\anaconda3\envs\Cryptography\Lib\threading.py", line 1142, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started`

**Comment by ScriptSlayer0** [comment]
@HarbingerOfFire Any idea about this?:
Traceback (most recent call last):
  File "d:\github\bivittatusDB\BivittatusDB\BDB_tb.py", line 38, in __del__
    self.stop_log()
  File "d:\github\bivittatusDB\BivittatusDB\BDB_tb.py", line 35, in stop_log
    self.logger.stop()
  File "d:\github\bivittatusDB\BivittatusDB\tty_log.py", line 47, in stop
    self.thread.join()

**Comment by HarbingerOfFire** [comment]
I think it should be fixed now

**Comment by ScriptSlayer0** [comment]
Fixed just now

**Comment by HarbingerOfFire** [comment]
Looks like I had to forgot to make sure a logger was started before closing the logger during the deletion of the table. (e.g. closing something that didn't exist)

**Comment by ScriptSlayer0** [comment]
When I do a keyboard break (ctr + c)
this appears:
Exception ignored in: <function logger.__del__ at 0x000001EC03153560>
Traceback (most recent call last):
  File ‘d:\githubDBivittatusDBivittatusDBDBivittatusDBDBtty_log.py’, line 12, in __del__
    os.remove(self.logfile)
FileNotFoundError: [WinError 2] System cannot find the specified file: ‘test/table1.dbl’.
Exception ignored in: <function logger.__del__ at 0x000001EC03153560>
Traceback (most recent call last):
  File ‘d:\githubDBivittatusDBivittatusDBivittatusDBDBtty_log.py’, line 12, in __del__
    os.remove(self.logfile)
FileNotFoundError: [WinError 2] System cannot find the specified file: ‘test/table1.dbl’.

Is related to that problem?

**Comment by ScriptSlayer0** [comment]
‘test/table1.dbl’. Is a table that I was using for debbuging

**Comment by HarbingerOfFire** [comment]
Yeah, cause the file isn't created until the logger is started. One sec, fix coming.

**Comment by HarbingerOfFire** [comment]
Updated

**Comment by ScriptSlayer0** [comment]
> OK, I think we should go in and implement the log files, probably replacing infomessage
If it works better than infomessage and performs better, that's fine with me.
(I am modulating the functions to operate the tables, to reduce duplicate code and avoid making more hot fixes in the future).

**Comment by HarbingerOfFire** [comment]
It looks like it's almost time to merge. Are there any more edits you want to make?

**Comment by ScriptSlayer0** [comment]
I just need a few changes in removing, updating and metadata.
After that I would give it enough to merge.

**Comment by HarbingerOfFire** [comment]
Sounds good! Thanks for the input!

**Comment by HarbingerOfFire** [comment]
Note, DBED-0003 has been updated to match the new features of the implementation

**Comment by ScriptSlayer0** [comment]
I'm working on it, but I have found a issue that blocked me to test, a circular import form encrypt.py

**Comment by ScriptSlayer0** [comment]
```
Traceback (most recent call last):
  File "d:\github\bivittatusDB\BivittatusDB\bdb_aggregate.py", line 8, in <module>
    import encrypt
  File "d:\github\bivittatusDB\BivittatusDB\encrypt.py", line 2, in <module>
    from bdb_aggregate import infomessage
ImportError: cannot import name 'infomessage' from partially initialized module 'bdb_aggregate' (most likely due to a circular import) (d:\github\bivittatusDB\BivittatusDB\bdb_aggregate.py)

**Comment by HarbingerOfFire** [comment]
Maybe we should remove infomessage from encrypt since an error in encryption shouldn't be suppressed. That way it should automatically send the trace.

**Comment by HarbingerOfFire** [comment]
It's either that or move the share module to BivittatusDB.py

**Comment by ScriptSlayer0** [comment]
Only a few changes need to be made to metadata.py
(Almost completely finished)

**Comment by HarbingerOfFire** [comment]
If you think it should be done let's do it
