### ISSUE TITLE
Encrypted by Default?

### ISSUE THREAD

**Issue by HarbingerOfFire** [HarbingerOfFire/bivittatusDB#7]
@ScriptSlayer0 
When rewriting the I/O manager, I realize that I can now easily set this to encrypt files by default or not. What would your input be? Should it be default or should it be up to the user to enable it?

**Comment by ScriptSlayer0** [comment]
I think that this can be done optionally and that the user can decide when creating the database if he wants it to be encrypted or not.

**Comment by HarbingerOfFire** [comment]
Thank you for the input, I'll put that in.
