### ISSUE TITLE
Autocommit Corrupting datafile

### ISSUE THREAD

**Issue by HarbingerOfFire** [HarbingerOfFire/bivittatusDB#8]
When I start using auto commit, I can add two rows to a table, but during the second run, it removes the data from the metadata segment of the database file. I can't figure out why this is happening.

**To Reproduce**
In the example file contained in the src directory, add the line `tb1@bdb.ON` to turn on auto commit, and then run that. It doesn't error with a normal traceback, but windows says it exits with code -1073740791. You'll also notice that it doesn't run the print table step. 

**Screenshots**
If you can read this, you'll see the metadata table here is intact.
![image](https://github.com/HarbingerOfFire/bivittatusDB/assets/154275077/a3142b2f-834d-4694-9de1-5af7152e46db)
Here is the same data after the adding of the second table. That metadata is corrupted: 
![image](https://github.com/HarbingerOfFire/bivittatusDB/assets/154275077/d600fdb3-35be-4144-b3e8-d1e4139013a9)

**Comment by ScriptSlayer0** [comment]
Can you provide a video reproducing this issue?
It can help to see how it runs on your system and maybe can help to get a fix for this.

**Comment by HarbingerOfFire** [comment]
you should be able to view it [here](https://mega.nz/file/0OtVgCCT#Dimp-7bGzkkstsEn5CSysp7A6WwaG4br-J4-_DpgVlc)

**Comment by ScriptSlayer0** [comment]
Only happens when I run auto_commit:
`Traceback (most recent call last):
  File "d:\github\bivittatusDB\src\ex_auto_commit.py", line 2, in <module>
    import BivittatusDB as bdb
  File "d:\github\bivittatusDB\src\BivittatusDB.py", line 2, in <module>
    from BDB_tb import *
  File "d:\github\bivittatusDB\src\BDB_tb.py", line 1, in <module>
    import datetime, BDB_metadata
  File "d:\github\bivittatusDB\src\BDB_metadata.py", line 4, in <module>
    from BDB_io import DBio_lib
  File "d:\github\bivittatusDB\src\BDB_io.py", line 4, in <module>
    io_lib = ctypes.CDLL("./lib_bdb.so")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Unai\anaconda3\envs\Cryptography\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'D:\github\bivittatusDB\lib_bdb.so' (or one of its dependencies). Try using the full path with constructor syntax.`

**Comment by HarbingerOfFire** [comment]
Are you running from inside the sec file?

**Comment by HarbingerOfFire** [comment]
it looks like the code isn't run from the folder though, since it's looking for `D:\github\bivittatusDB\lib_bdb.so` when it should be looking for `D:\github\bivittatusDB\src\lib_bdb.so`

**Comment by ScriptSlayer0** [comment]
What?, but in my computer appears in this path
![image](https://github.com/user-attachments/assets/b4349d5f-ce66-4f16-800c-e37e26b08847)

**Comment by HarbingerOfFire** [comment]
yeah, but what directory is your ide located in?

**Comment by ScriptSlayer0** [comment]
C:\Users\dev\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Visual Studio Code

**Comment by HarbingerOfFire** [comment]
I meant like what folder is it opened to. Like: 
![image](https://github.com/user-attachments/assets/370c1504-835e-4294-9882-4f89feca62ae)

**Comment by ScriptSlayer0** [comment]
![image](https://github.com/user-attachments/assets/2e2e3bf5-da03-48a3-af80-1ef4a0fa541a)

**Comment by HarbingerOfFire** [comment]
interesting, right folder, but the file isn't there?

**Comment by ScriptSlayer0** [comment]
If I take out the lib_bdb.so file it doesn't give error, but if it's inside src it jumps

**Comment by HarbingerOfFire** [comment]
in the `bdb_io.py` file add the following lines before loading the c-lib.
```Python3
from pathlib import Path
print(Path("mydir/myfile.txt").absolute())
``

**Comment by ScriptSlayer0** [comment]
`D:\github\bivittatusDB\mydir\myfile.txt`

**Comment by HarbingerOfFire** [comment]
Yeah, the code seems to be running outside of the src directory for you. That is weird

**Comment by ScriptSlayer0** [comment]
Which python version are you running?
Maybe it's the interpreter version of python (to be ruled out)

**Comment by HarbingerOfFire** [comment]
3.12

**Comment by ScriptSlayer0** [comment]
@HarbingerOfFire I have made a test, using the next code:

```
import os
current_dir = os.path.dirname(os.path.realpath(__file__))
print("This is the current dir:",current_dir)
```

And the output it's:
`This is the current dir: D:\github\bivittatusDB\src`
When this file it's out of src or inside in the same directory the output is the same directory

**Comment by HarbingerOfFire** [comment]
Yeah, that's telling you the path of the file you're running. Try replacing `__file__` with `lib_bdb.so` and is probably going to give `This is the current dir: D:\github\bivittatusDB`

**Comment by HarbingerOfFire** [comment]
I'm going to go ahead and close this as I'm making a lot of updates for the file-per-table version which should hopefully fix the initial error. Hopefully when you sync your changes it will solve your errors as well.

**Comment by ScriptSlayer0** [comment]
@HarbingerOfFire I have a very strange question. In VS in the terminal the output is: `This is the current directory: D:\github\bivittatusDB`
But using CMD running the code the output is:
`This is the current directory: D:\github\bivittatusDBDB\src`
Is it a problem with VS or what is going on?
CMD:
![image](https://github.com/user-attachments/assets/81fe3a99-009b-4353-a845-637cabd4e7cf)
VS:
![image](https://github.com/user-attachments/assets/273f9edc-6d67-4560-9335-8bc51c4049cf)

**Comment by HarbingerOfFire** [comment]
Notice the difference in the prompt. CMD has you in the src/ directory but in VS you are in it's parent folder. Just to make sure, this is Visual Studio Code and not Visual Studio \<Year>, right?

**Comment by HarbingerOfFire** [comment]
@ScriptSlayer0 If you are in VSCode, you can use ctrl+k, ctrl+o then you can select the /src directory. Then run the test.py code again

**Comment by HarbingerOfFire** [comment]
Actually, the last update should fix your problem. Let me know if you still experience the error

**Comment by ScriptSlayer0** [comment]
He mejorado el código al principio estuve haciendo bastantes pruebas para conseguirlo.
Code:
```
import os

def find_path(file_name):
    for root, dirs, files in os.walk('/'):
        if file_name in files:
            return os.path.join(root, file_name)

file_path = find_path('lib_bdb.so')

if file_path:
    print(f"The file 'lib_bdb.so' is located in: {file_path}")
else:
    print("File 'lib_bdb.so' was not found.")
```
Output:
`The file 'lib_bdb.so' is located in: /github\BivitattusDatabase\lib_bdb.so`

**Comment by ScriptSlayer0** [comment]
> Actually, the last update should fix your problem. Let me know if you still experience the error

I already working: ex_autocommit.py, ex_use_table.py

**Comment by HarbingerOfFire** [comment]
That means the table is empty. add a few rows and then print it.

**Comment by ScriptSlayer0** [comment]
I think `ex_add_rows.py` it's bugged, after adding rows to the table throws when you are using the same table like a blank table.

**Comment by HarbingerOfFire** [comment]
`ex_add_rows.py` doesn't commit the changes in any way. They are just staged in memory. Either turn on autocommit (`ex_auto_commit.py`) or save the change (`ex_save.py`) and retry.

**Comment by HarbingerOfFire** [comment]
I tested the example files and they all work as expected. I pushed this to release as version 4.1.0. I'm going to go ahead and lock this issue. If you find anything else you can always open a new issue.
